ALTER TABLE users ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE tasks ADD COLUMN type VARCHAR(20) DEFAULT 'NODE' NOT NULL;
ALTER TABLE tasks ADD CONSTRAINT check_task_type CHECK (type IN ('NODE', 'TREE'));
ALTER TABLE tasks ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE tasks ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

CREATE TABLE sub_items(
    sub_item_id BIGSERIAL PRIMARY KEY,
    text VARCHAR(200) NOT NULL,
    is_done BOOLEAN NOT NULL DEFAULT FALSE,
    parent_id BIGINT,
    task_id BIGINT NOT NULL,
    CONSTRAINT fk_subitem_parent FOREIGN KEY (parent_id) REFERENCES sub_items(sub_item_id) ON DELETE CASCADE,
    CONSTRAINT fk_subitem_task FOREIGN KEY (task_id) REFERENCES tasks(task_id) ON DELETE CASCADE
);